server:
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file-upload?serverTimezone=Asia/Seoul
    username: sbsst
    password: sbs123414
  jpa:
    hibernate:
#      ddl-auto: create

cloud:
  aws:
    credentials:
      accessKey: AKIARY6OP5VYI4W44GY6
      secretKey: 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

    s3:
      bucket: file-upload-heungjin
      dir: /
    region:
      static: ap-northeast-2
    stack:
      auto: false